name: web-thi-ai-bao-mat
services:
  web-thi-ai-bao-mat:
    platform: linux/amd64
    image: ghcr.io/trankhanhduy2929-beep/web-thi-ai-bao-mat:latest
    container_name: web-thi-ai-bao-mat
    restart: unless-stopped
    environment:
      - PORT=80
      - DOS_API_KEY=
      - GROQ_API_KEY=
    ports:
      - target: 80
        published: "1234"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/web-thi-ai-bao-mat/data
        target: /app/data
    network_mode: bridge
    privileged: false

x-casaos:
  architecture:
    - amd64
    - arm64
  architectures:
    - amd64
    - arm64
  author: self
  category: Education
  hostname: ""
  icon: https://png.pngtree.com/png-clipart/20231218/original/pngtree-icon-for-achievements-in-competitions-and-success-from-dualcolored-photo-png-image_13880222.png
  index: /
  is_uncontrolled: false
  main: web-thi-ai-bao-mat
  port_map: "1234"
  scheme: http
  store_app_id: web-thi-ai-bao-mat
  title:
    custom: ""
    en_us: Web Thi AI Bảo Mật
