name: shop-admin
services:
  shop-admin:
    image: ghcr.io/trankhanhduy2929-beep/shop-admin:latest
    container_name: shop-admin
    restart: unless-stopped
    environment:
      - PORT=8080
      - APP_NAME=Shop Admin
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=xxxxx
      - SESSION_SECRET=replace-with-a-long-random-secret
    ports:
      - target: 8080
        published: "1235"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shop-admin/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/shop-admin/uploads
        target: /app/uploads
    network_mode: bridge
    privileged: false

x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2CLb-XoCLP5RL1Y-L8B8cGt24jaZGA7XvxQ&s
  index: /
  is_uncontrolled: false
  port_map: "1235"
  scheme: http
  store_app_id: shop-admin
  title:
    custom: ""
    en_us: shop-admin
