name: personal-timesheet
services:
  personal-timesheet:
    platform: linux/amd64
    image: ghcr.io/trankhanhduy2929-beep/personal-timesheet:latest
    container_name: personal-timesheet
    restart: unless-stopped
    environment:
      - PORT=8080
      - JWT_SECRET=change-this-secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=xxxxx
      - ADMIN_FULL_NAME=Quản trị viên
      - ALLOW_ADMIN_VIEW_PASSWORDS=true
    ports:
      - target: 8080
        published: "5555"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/personal_timesheet/data
        target: /app/data
    network_mode: bridge
    privileged: false

x-casaos:
  architecture:
    - amd64
    - arm64
  architectures:
    - amd64
    - arm64
  author: self
  category: Productivity
  hostname: ""
  icon: https://fsviet.com/image/data/ch%E1%BA%A5m%20c%C3%B4ng%201.jpg
  index: /
  is_uncontrolled: false
  main: personal-timesheet
  port_map: "5555"
  scheme: http
  store_app_id: personal-timesheet
  title:
    custom: ""
    en_us: Personal Timesheet
