name: sincere_renaud
services:
  9router:
    cpu_shares: 10
    command: []
    container_name: 9router
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - DATA_DIR=/app/data
    hostname: 9router
    image: decolua/9router:latest
    labels:
      icon: https://9router.com/9router-hero.jpg
    ports:
      - target: 20128
        published: "20128"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/9router
        target: /app/data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: self
  category: Network
  hostname: ""
  icon: https://9router.com/9router-hero.jpg
  index: /
  is_uncontrolled: false
  main: 9router
  port_map: "20128"
  scheme: http
  store_app_id: 9router
  title:
    custom: ""
    en_us: 9Router
