name: picoclaw
services:
  launcher:
    cpu_shares: 10
    command: []
    container_name: picoclaw-launcher
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PICOCLAW_LAUNCHER_TOKEN=xxxxxxx
      - TZ=Asia/Ho_Chi_Minh
    hostname: picoclaw-launcher
    image: sipeed/picoclaw:launcher
    labels:
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/picoclaw.webp
    ports:
      - target: 18800
        published: "18800"
        protocol: tcp
      - target: 18790
        published: "18790"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/picoclaw/docker/data
        target: /root/.picoclaw
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  architecture:
    - amd64
    - arm64
  architectures:
    - amd64
    - arm64
  author: self
  category: AI
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/picoclaw.webp
  index: /
  is_uncontrolled: false
  main: launcher
  port_map: "18800"
  ports:
    - container: 18800
      host: 18800
      protocol: tcp
  scheme: http
  store_app_id: picoclaw-ai
  title:
    custom: ""
    en_us: PicoClaw AI
  web_ui: http://[IP]:18800
