name: yduc-booking-v2
services:
  yduc-booking-v2:
    image: ghcr.io/trankhanhduy2929-beep/yduc-booking-v2:latest
    container_name: yduc-booking-v2
    restart: unless-stopped
    environment:
      - PORT=3000
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT_ID=
      - ZALO_WEBHOOK_URL=
      - ZALO_WEBHOOK_SECRET=
    ports:
      - target: 3000
        published: "3008"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yduc-booking-v2/data
        target: /app/data
    network_mode: bridge
    privileged: false

x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://bo-api.medpro.com.vn:5000/static/images/medpro/app/image/goi_kham.png?t=2333333
  index: /
  is_uncontrolled: false
  port_map: "3008"
  scheme: http
  store_app_id: yduc-booking-v2
  title:
    custom: ""
    en_us: yduc-booking-v2
